sudo: required
language: java
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
jdk:
- oraclejdk8
services: postgresql
addons:
  postgresql: 9.4
before_install:
- env
- export postgresql_version=${postgresDriverVersion}
- export liquibase_version=${liquibaseVersion}
- export schemacrawler_version=${schemacrawlerVersion}
- export JAVA_OPTS="-Xmx2560m -XX:-UseGCOverheadLimit"
- echo $JAVA_OPTS
- sudo chown -R travis ./travis/pull_install_script.sh
- sudo chmod +x ./travis/pull_install_script.sh
- ./travis/pull_install_script.sh
- cd script
- ./install.sh
- echo "deploying ${appName}  database."
- dropdb --if-exists ${appName}
- psql -c 'create database ${appName} ;' -U postgres
- cd ../${appName}
- liquibase --driver=org.postgresql.Driver --username=postgres --url=jdbc:postgresql:${appName}  --defaultSchemaName=public --changeLogFile=db.changelog.xml --logLevel=debug update
- cd ..
install:
- mvn exec:exec
notifications:
  slack:
    secure: ## A SAISIR ##
